language: php

php:
        - "5.4"
        - "5.5"

script: "VERBOSE=true ./vendor/bin/tester -s tests/"

before_script:
        - composer self-update
        - composer install --dev
        - sudo chmod 777 -R ./
